FROM openjdk:8-jre-alpine

RUN mkdir /app

WORKDIR /app

COPY target/acmeair-bookingservice-java-3.3.jar /app/kz.jar

EXPOSE 9080

ENV JAEGER_SERVICE_NAME=jaeger-service
ENV JAEGER_AGENT_HOST=jaeger
ENV JAEGER_REPORTER_LOG_SPANS=false
ENV JAEGER_SAMPLER_TYPE=const
ENV JAEGER_SAMPLER_PARAM=1

CMD ["java", "-DcustomerClient/mp-rest/url=${CUSTOMER_SERVICE_LOC}", "-DflightClient/mp-rest/url=${FLIGHT_SERVICE_LOC}" , "-jar", "kz.jar"]

