FROM openjdk:11-jre-slim
WORKDIR /helidon

# Copy the binary built in the 1st stage
COPY target/acmeair-bookingservice-java.jar ./helidon.jar
COPY target/libs ./libs

CMD ["java","-Dhttp.keepalive=true", "-Dhttp.maxConnections=100","-jar", "helidon.jar"]

EXPOSE 9080
